# Generated by Django 4.0.10 on 2023-11-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorrecord',
            name='temperature',
        ),
    ]
