name: Docker Login

on:
  push:
    branches:
      - development

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      run: |
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | docker login --username AWS --password-stdin "${{ secrets.ECR_REGISTRY }}"

    - name: Build and Push Docker Image
      run: |
        docker build -t "${{ secrets.ECR_REGISTRY }}/mi-aplicacion:${{ github.sha }}" .
        docker push "${{ secrets.ECR_REGISTRY }}/mi-aplicacion:${{ github.sha }}"
