name: Build and Push Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      run: |
        AWS_REGION="us-east-1"
        AWS_REGISTRY_URL="711704289087.dkr.ecr.us-east-1.amazonaws.com"        
        TOKEN=$(aws ecr get-login-password --region $AWS_REGION)        
        echo $TOKEN | docker login --username AWS --password-stdin $AWS_REGISTRY_URL

    - name: Build and Push Docker Image
      run: |
        docker build -t 711704289087.dkr.ecr.us-east-1.amazonaws.com/mi-aplicacion:${{ github.sha }} .
        docker push 711704289087.dkr.ecr.us-east-1.amazonaws.com/mi-aplicacion:${{ github.sha }}
