name: Build and Push Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      run: |
        AWS_REGION="us-east-1"
        AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_REGISTRY_URL="711704289087.dkr.ecr.us-east-1.amazonaws.com"
        
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
        
        TOKEN=$(aws ecr get-login-password --region $AWS_REGION)
        
        echo $TOKEN | docker login --username AWS --password-stdin $AWS_REGISTRY_URL

    - name: Build and Push Docker Image
      run: |
        docker build -t 711704289087.dkr.ecr.us-east-1.amazonaws.com/django-app-repo:${{ github.sha }} .
        docker push 711704289087.dkr.ecr.us-east-1.amazonaws.com/django-app-repo:${{ github.sha }}
